#!/bin/bash
export EDITOR=vim;
export VISUAL=nvim; #Nano is the main editor
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export PATH="$HOME/.local/bin:$PATH";
export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH";
## HERE I'LL EXPORT SOME STUFF TO CLEAN MY HOME DIR
export GEM_HOME="$XDG_DATA_HOME"/gem;
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem;
export KDEHOME="$XDG_CONFIG_HOME"/kde;
export MPLAYER_HOME="$XDG_CONFIG_HOME"/mplayer;
#colorman
if $_isxrunning; then
  export PAGER=less
  export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
  export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
  export LESS_TERMCAP_me=$'\E[0m'           # end mode
  export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
  export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
  export LESS_TERMCAP_ue=$'\E[0m'           # end underline
  export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
fi

export TIME_STYLE="+%Y-%m-%d %H:%M:%S %z"
